CREATE TABLE public.addresses (
  id SERIAL PRIMARY KEY,
  "fullName" CHARACTER VARYING(255) NOT NULL,
  address CHARACTER VARYING(255) NOT NULL,
  "addressLine1" CHARACTER VARYING(255) NOT NULL,
  landmark CHARACTER VARYING(255),
  pincode INTEGER,
  city CHARACTER VARYING(255),
  state CHARACTER VARYING(255),
  "isActive" BOOLEAN DEFAULT false,
  "userId" INTEGER NOT NULL,
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL
);
